Özellik Ölçekleme, verilerde bulunan bağımsız özellikleri sabit bir aralıkta standartlaştırma tekniğidir. 

Çok değişken büyüklükleri veya değerleri veya birimleri işlemek için veri ön işleme sırasında gerçekleştirilir. 

Özellik ölçeklendirme yapılmazsa, bir makine öğrenimi algoritması, değerlerin biriminden bağımsız olarak daha büyük değerleri, daha yükseği tartma ve daha küçük değerleri daha düşük değerler olarak kabul etme eğilimindedir.

**Örnek:** Bir algoritma öznitelik ölçekleme yöntemini kullanmıyorsa, 3000 metre değerini 5 km'den büyük kabul edebilir ancak bu aslında doğru değildir ve bu durumda algoritma yanlış tahminler verecektir. Bu nedenle, tüm değerleri aynı büyüklüklere getirmek için Özellik Ölçeklendirmeyi kullanıyoruz ve böylece bu sorunu çözüş oluyoruz.

##Özellik Ölçekleme gerçekleştirme teknikleri
En önemli iki tanesini göz önünde bulunduralım:

**Min-Maks Normalleştirme:** 
Bu teknik, bir özelliği veya gözlem değerini 0 ile 1 arasında dağılım değeriyle yeniden ölçeklendirir.

image.png

**Standardizasyon:** Bir öznitelik değerini, 0 ortalama değeri ve varyansı 1 olacak şekilde yeniden ölçeklendiren çok etkili bir tekniktir.

image.png



##Örnekler


In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from  sklearn import preprocessing

In [25]:
data = pd.read_csv("/content/Data_for_Missing_Values.csv")
data.head()

x = data.iloc[:,1:3].values
print("\n Orjinal data görüntüsü :\n",x)


 Orjinal data görüntüsü :
 [[4.4e+01 7.2e+04]
 [2.7e+01 4.8e+04]
 [3.0e+01 5.4e+04]
 [3.8e+01 6.1e+04]
 [4.0e+01     nan]
 [3.5e+01 5.8e+04]
 [    nan 5.2e+04]
 [4.8e+01 7.9e+04]
 [5.0e+01 8.3e+04]
 [3.7e+01 6.7e+04]]


Eksik Değerlerin İşlenmesi


In [24]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))

x_after_min_max_scaler = min_max_scaler.fit_transform(x)

print('\n Min max Scaler sonrası :\n',x_after_min_max_scaler)


 Min max Scaler sonrası :
 [[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739        nan]
 [0.34782609 0.28571429]
 [       nan 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]


In [26]:
standardisation = preprocessing.StandardScaler()

x_after_Standardisation = Standardisation.fit_transform(x)

print("\n Standardizasyon sonrası :\n",x_after_Standardisation)


 Standardizasyon sonrası :
 [[ 0.71993143  0.71101276]
 [-1.62367514 -1.36437583]
 [-1.21009751 -0.84552869]
 [-0.10722383 -0.24020701]
 [ 0.16849459         nan]
 [-0.52080146 -0.49963059]
 [        nan -1.01847774]
 [ 1.27136827  1.31633443]
 [ 1.54708669  1.66223253]
 [-0.24508304  0.27864014]]
